GET http://localhost:3001/todos

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Get the water"
}

###
DELETE http://localhost:3001/todo/delete/65b4a4b859db99d900b68e4c

###
PUT http://localhost:3001/todo/complete/65b4ae81f454e0b410686fa0